name: github pages

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
Build_and_Deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
    uses: peaceiris/actions-hugo@v2
    with:
        hugo-version: '0.63.2'
    - name: Build
    run: hugo --minify
    - name: Deploy to S3
      run: hugo deploy --force --maxDeletes -1 --invalidateCDN
      env:
        AWS_ACCESS_KEY_ID: $
        AWS_SECRET_ACCESS_KEY: $